### ISSUE TITLE
Добавить зависимость от пакета i18n

### ISSUE THREAD

**Issue by Compolomus** [v-dem/queasy-validation#1]
Вообще плохая практика сильно связывать компоненты, захочет кто нибудь взять пакет, а ему композер половину фв в вендора зальёт

**Comment by v-dem** [comment]
Я же писал на Хабре, что как раз переделываю всё чтоб избавиться от зависимостей.

**Comment by v-dem** [comment]
И сейчас работаю над queasy-db, а почти готовы только queasy-config и queasy-log

**Comment by Compolomus** [comment]
Да я потом уже глянул остальные репы, и понял, там пока многое не готово. 
Я маленькую орм писал кстати, но совсем маленькую, чисто в практических целях
https://github.com/drmvc/orm

**Comment by v-dem** [comment]
Остальные пакеты остались от первой попытки, когда оно всё было в одном репозитории и само собой связано, потом я разделил по разным и решил переписать по-новому.

Глянул, да, очень компактно. Я тоже сначала подумывал про ORM и/или ActiveRecord (я имею в виду более навороченную, с учетом вторичных ключей и т.д.) но решил остановиться на обертке над PDO, так как писалось это для себя а мне часто приходится работать с существующими БД, в то время как ORM как правило накладывают определенные ограничения на структуру, например требуют наличия уникального ключа.

**Comment by Compolomus** [comment]
Думаю можно закрывать))

**Comment by Compolomus** [comment]
Я именно не хотел писать AR , дурной тон. Применил другой паттерн
